#!/bin/sh -ex

label="${1-Toggle}"
stem="`echo \"$label\" | tr A-Z a-z`"

make examples/pixmaps/make-button

./make-button -o "${stem}-up.ppm" "$label" up
pnmtopng "${stem}-up.ppm" > "${stem}-up.png"

./make-button -o "${stem}-down.ppm" "$label" down
pnmtopng "${stem}-down.ppm" > "${stem}-down.png"
open "${stem}"-{up,down}.png
open /Applications/Emacs.app

./img-to-button "${label}"                      \
                "${stem}-up.ppm"                \
                "${stem}-down.ppm"              \
                -o "${stem}-button.h"
